/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: t9db.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "t9db.pb-c.h"
void   stored_word__init
                     (StoredWord         *message)
{
  static const StoredWord init_value = STORED_WORD__INIT;
  *message = init_value;
}
size_t stored_word__get_packed_size
                     (const StoredWord *message)
{
  assert(message->base.descriptor == &stored_word__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stored_word__pack
                     (const StoredWord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stored_word__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stored_word__pack_to_buffer
                     (const StoredWord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stored_word__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StoredWord *
       stored_word__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StoredWord *)
     protobuf_c_message_unpack (&stored_word__descriptor,
                                allocator, len, data);
}
void   stored_word__free_unpacked
                     (StoredWord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stored_word__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stored_token_edge__init
                     (StoredTokenEdge         *message)
{
  static const StoredTokenEdge init_value = STORED_TOKEN_EDGE__INIT;
  *message = init_value;
}
size_t stored_token_edge__get_packed_size
                     (const StoredTokenEdge *message)
{
  assert(message->base.descriptor == &stored_token_edge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stored_token_edge__pack
                     (const StoredTokenEdge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stored_token_edge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stored_token_edge__pack_to_buffer
                     (const StoredTokenEdge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stored_token_edge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StoredTokenEdge *
       stored_token_edge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StoredTokenEdge *)
     protobuf_c_message_unpack (&stored_token_edge__descriptor,
                                allocator, len, data);
}
void   stored_token_edge__free_unpacked
                     (StoredTokenEdge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stored_token_edge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stored_token__init
                     (StoredToken         *message)
{
  static const StoredToken init_value = STORED_TOKEN__INIT;
  *message = init_value;
}
size_t stored_token__get_packed_size
                     (const StoredToken *message)
{
  assert(message->base.descriptor == &stored_token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stored_token__pack
                     (const StoredToken *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stored_token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stored_token__pack_to_buffer
                     (const StoredToken *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stored_token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StoredToken *
       stored_token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StoredToken *)
     protobuf_c_message_unpack (&stored_token__descriptor,
                                allocator, len, data);
}
void   stored_token__free_unpacked
                     (StoredToken *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stored_token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stored_trie_node__init
                     (StoredTrieNode         *message)
{
  static const StoredTrieNode init_value = STORED_TRIE_NODE__INIT;
  *message = init_value;
}
size_t stored_trie_node__get_packed_size
                     (const StoredTrieNode *message)
{
  assert(message->base.descriptor == &stored_trie_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stored_trie_node__pack
                     (const StoredTrieNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stored_trie_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stored_trie_node__pack_to_buffer
                     (const StoredTrieNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stored_trie_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StoredTrieNode *
       stored_trie_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StoredTrieNode *)
     protobuf_c_message_unpack (&stored_trie_node__descriptor,
                                allocator, len, data);
}
void   stored_trie_node__free_unpacked
                     (StoredTrieNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stored_trie_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   t9_database__init
                     (T9Database         *message)
{
  static const T9Database init_value = T9_DATABASE__INIT;
  *message = init_value;
}
size_t t9_database__get_packed_size
                     (const T9Database *message)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t t9_database__pack
                     (const T9Database *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t t9_database__pack_to_buffer
                     (const T9Database *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
T9Database *
       t9_database__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (T9Database *)
     protobuf_c_message_unpack (&t9_database__descriptor,
                                allocator, len, data);
}
void   t9_database__free_unpacked
                     (T9Database *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &t9_database__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stored_word__field_descriptors[2] =
{
  {
    "word",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StoredWord, word),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StoredWord, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stored_word__field_indices_by_name[] = {
  1,   /* field[1] = freq */
  0,   /* field[0] = word */
};
static const ProtobufCIntRange stored_word__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stored_word__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StoredWord",
  "StoredWord",
  "StoredWord",
  "",
  sizeof(StoredWord),
  2,
  stored_word__field_descriptors,
  stored_word__field_indices_by_name,
  1,  stored_word__number_ranges,
  (ProtobufCMessageInit) stored_word__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stored_token_edge__field_descriptors[2] =
{
  {
    "target_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StoredTokenEdge, target_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StoredTokenEdge, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stored_token_edge__field_indices_by_name[] = {
  1,   /* field[1] = freq */
  0,   /* field[0] = target_id */
};
static const ProtobufCIntRange stored_token_edge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stored_token_edge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StoredTokenEdge",
  "StoredTokenEdge",
  "StoredTokenEdge",
  "",
  sizeof(StoredTokenEdge),
  2,
  stored_token_edge__field_descriptors,
  stored_token_edge__field_indices_by_name,
  1,  stored_token_edge__number_ranges,
  (ProtobufCMessageInit) stored_token_edge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stored_token__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StoredToken, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StoredToken, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StoredToken, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edges",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StoredToken, n_edges),
    offsetof(StoredToken, edges),
    &stored_token_edge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stored_token__field_indices_by_name[] = {
  3,   /* field[3] = edges */
  1,   /* field[1] = freq */
  0,   /* field[0] = id */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange stored_token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stored_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StoredToken",
  "StoredToken",
  "StoredToken",
  "",
  sizeof(StoredToken),
  4,
  stored_token__field_descriptors,
  stored_token__field_indices_by_name,
  1,  stored_token__number_ranges,
  (ProtobufCMessageInit) stored_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stored_trie_node__field_descriptors[6] =
{
  {
    "node_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StoredTrieNode, has_node_index),
    offsetof(StoredTrieNode, node_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StoredTrieNode, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StoredTrieNode, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokens",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StoredTrieNode, n_tokens),
    offsetof(StoredTrieNode, tokens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StoredTrieNode, n_children),
    offsetof(StoredTrieNode, children),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "words",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StoredTrieNode, n_words),
    offsetof(StoredTrieNode, words),
    &stored_word__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stored_trie_node__field_indices_by_name[] = {
  1,   /* field[1] = character */
  4,   /* field[4] = children */
  2,   /* field[2] = freq */
  0,   /* field[0] = node_index */
  3,   /* field[3] = tokens */
  5,   /* field[5] = words */
};
static const ProtobufCIntRange stored_trie_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor stored_trie_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StoredTrieNode",
  "StoredTrieNode",
  "StoredTrieNode",
  "",
  sizeof(StoredTrieNode),
  6,
  stored_trie_node__field_descriptors,
  stored_trie_node__field_indices_by_name,
  1,  stored_trie_node__number_ranges,
  (ProtobufCMessageInit) stored_trie_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor t9_database__field_descriptors[2] =
{
  {
    "tokens",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(T9Database, n_tokens),
    offsetof(T9Database, tokens),
    &stored_token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roots",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(T9Database, n_roots),
    offsetof(T9Database, roots),
    &stored_trie_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned t9_database__field_indices_by_name[] = {
  1,   /* field[1] = roots */
  0,   /* field[0] = tokens */
};
static const ProtobufCIntRange t9_database__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor t9_database__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "T9Database",
  "T9Database",
  "T9Database",
  "",
  sizeof(T9Database),
  2,
  t9_database__field_descriptors,
  t9_database__field_indices_by_name,
  1,  t9_database__number_ranges,
  (ProtobufCMessageInit) t9_database__init,
  NULL,NULL,NULL    /* reserved[123] */
};
