/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: t9db.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "t9db.pb-c.h"
void   token_edge__init
                     (TokenEdge         *message)
{
  static const TokenEdge init_value = TOKEN_EDGE__INIT;
  *message = init_value;
}
size_t token_edge__get_packed_size
                     (const TokenEdge *message)
{
  assert(message->base.descriptor == &token_edge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t token_edge__pack
                     (const TokenEdge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &token_edge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t token_edge__pack_to_buffer
                     (const TokenEdge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &token_edge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TokenEdge *
       token_edge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TokenEdge *)
     protobuf_c_message_unpack (&token_edge__descriptor,
                                allocator, len, data);
}
void   token_edge__free_unpacked
                     (TokenEdge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &token_edge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   token__init
                     (Token         *message)
{
  static const Token init_value = TOKEN__INIT;
  *message = init_value;
}
size_t token__get_packed_size
                     (const Token *message)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t token__pack
                     (const Token *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t token__pack_to_buffer
                     (const Token *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Token *
       token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Token *)
     protobuf_c_message_unpack (&token__descriptor,
                                allocator, len, data);
}
void   token__free_unpacked
                     (Token *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trie_node__init
                     (TrieNode         *message)
{
  static const TrieNode init_value = TRIE_NODE__INIT;
  *message = init_value;
}
size_t trie_node__get_packed_size
                     (const TrieNode *message)
{
  assert(message->base.descriptor == &trie_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trie_node__pack
                     (const TrieNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trie_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trie_node__pack_to_buffer
                     (const TrieNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trie_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrieNode *
       trie_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrieNode *)
     protobuf_c_message_unpack (&trie_node__descriptor,
                                allocator, len, data);
}
void   trie_node__free_unpacked
                     (TrieNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trie_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   t9_database__init
                     (T9Database         *message)
{
  static const T9Database init_value = T9_DATABASE__INIT;
  *message = init_value;
}
size_t t9_database__get_packed_size
                     (const T9Database *message)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t t9_database__pack
                     (const T9Database *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t t9_database__pack_to_buffer
                     (const T9Database *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &t9_database__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
T9Database *
       t9_database__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (T9Database *)
     protobuf_c_message_unpack (&t9_database__descriptor,
                                allocator, len, data);
}
void   t9_database__free_unpacked
                     (T9Database *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &t9_database__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor token_edge__field_descriptors[2] =
{
  {
    "target_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TokenEdge, target_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TokenEdge, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned token_edge__field_indices_by_name[] = {
  1,   /* field[1] = freq */
  0,   /* field[0] = target_id */
};
static const ProtobufCIntRange token_edge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor token_edge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TokenEdge",
  "TokenEdge",
  "TokenEdge",
  "",
  sizeof(TokenEdge),
  2,
  token_edge__field_descriptors,
  token_edge__field_indices_by_name,
  1,  token_edge__number_ranges,
  (ProtobufCMessageInit) token_edge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor token__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Token, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Token, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Token, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edges",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Token, n_edges),
    offsetof(Token, edges),
    &token_edge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned token__field_indices_by_name[] = {
  3,   /* field[3] = edges */
  1,   /* field[1] = freq */
  0,   /* field[0] = id */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Token",
  "Token",
  "Token",
  "",
  sizeof(Token),
  4,
  token__field_descriptors,
  token__field_indices_by_name,
  1,  token__number_ranges,
  (ProtobufCMessageInit) token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trie_node__field_descriptors[5] =
{
  {
    "node_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TrieNode, has_node_index),
    offsetof(TrieNode, node_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrieNode, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrieNode, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokens",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(TrieNode, n_tokens),
    offsetof(TrieNode, tokens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TrieNode, n_children),
    offsetof(TrieNode, children),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trie_node__field_indices_by_name[] = {
  1,   /* field[1] = character */
  4,   /* field[4] = children */
  2,   /* field[2] = freq */
  0,   /* field[0] = node_index */
  3,   /* field[3] = tokens */
};
static const ProtobufCIntRange trie_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor trie_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrieNode",
  "TrieNode",
  "TrieNode",
  "",
  sizeof(TrieNode),
  5,
  trie_node__field_descriptors,
  trie_node__field_indices_by_name,
  1,  trie_node__number_ranges,
  (ProtobufCMessageInit) trie_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor t9_database__field_descriptors[2] =
{
  {
    "tokens",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(T9Database, n_tokens),
    offsetof(T9Database, tokens),
    &token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roots",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(T9Database, n_roots),
    offsetof(T9Database, roots),
    &trie_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned t9_database__field_indices_by_name[] = {
  1,   /* field[1] = roots */
  0,   /* field[0] = tokens */
};
static const ProtobufCIntRange t9_database__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor t9_database__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "T9Database",
  "T9Database",
  "T9Database",
  "",
  sizeof(T9Database),
  2,
  t9_database__field_descriptors,
  t9_database__field_indices_by_name,
  1,  t9_database__number_ranges,
  (ProtobufCMessageInit) t9_database__init,
  NULL,NULL,NULL    /* reserved[123] */
};
